hook_add = '''
  " Vim
  let g:vimsyntax_noerror = 1

  " Bash
  let g:is_bash = 1

  " python.vim
  let g:python_highlight_all = 1

  " markdown colors
  " http://mattn.kaoriya.net/software/vim/20140523124903.htm
  let g:markdown_fenced_languages = [
        \   'css',
        \   'javascript',
        \   'js=javascript',
        \   'json=javascript',
        \   'xml',
        \   'vim',
        \   'php',
        \ ]

  " Folding
  " let g:php_folding = 1
  " let g:xml_syntax_folding = 1

  " Update filetype
  autocmd MyAutocmd BufWritePost * nested
        \ if &l:filetype ==# '' || exists('b:ftdetect')
        \   unlet! b:ftdetect
        \   filetype detect
        \ endif
'''

[ftplugin]
_ = '''
  " Disable automatically insert comment
  setl formatoptions-=ro
  setl formatoptions+=mMBl

  " Disable auto wrap
  if &l:textwidth != 70 && &filetype !=# 'help'
    setlocal textwidth=0
  endif

  " TODO
  " Use foldCCtext()
  " if &filetype !=# 'help'
  "   setlocal foldtext=FoldCCtext()
  " endif

  if !&l:modifiable
    setlocal nofoldenable
    setlocal foldcolumn=0

    if v:version >= 703
      setlocal colorcolumn=
    endif
  endif
'''

python = '''
  setlocal foldmethod=indent
'''

html = '''
  setlocal path+=./;/
'''

# TODO Smarty,phpの場合に path に追加する処理をvimrc_localに書く

vim = '''
  echomsg 'called'
  setlocal foldmethod=indent
'''

toml = '''
  syntax sync minlines=500
'''

help = '''
  setlocal iskeyword+=:
  setlocal iskeyword+=#
  setlocal iskeyword+=-
'''
