[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'source ~/.vim/rc/plugins/dein.rc.vim'

# colorschemeはLazyできないようなのでこっち
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <silent> <Leader>gs :<C-u>Gstatus<CR>
  nnoremap <silent> <Leader>gd :<C-u>Gvdiff<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
if = 'v:version == 704 && has("patch786") || v:version >= 705 || has("nvim")'

# TODO
# [[plugins]]
# repo = 'shawncplus/phpcomplete.vim'

[[plugins]]
repo = 'cespare/vim-toml'

# TODO
# [[plugins]]
# repo = 'elzr/vim-json'

[[plugins]]
repo = 'kana/vim-operator-user'

# TODO
# [[plugins]]
# repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'tpope/vim-repeat'

# TODO
# [[plugins]]
# repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# TODO
# [[plugins]]
# repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'nixprime/cpsm'
if = '!IsWindows()'
build = 'env PY3=ON ./install.sh'

# TODO
# [[plugins]]
# repo = 'chemzqm/denite-git'

[[plugins]]
repo = 'vim-scripts/smarty-syntax'

[[plugins]]
repo = 'lambdalisue/vim-diffa'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'jwalton512/vim-blade'
hook_add = '''
  autocmd MyAutocmd FileType blade
        \ let b:caw_wrap_oneline_comment = [ '{{--', '--}}' ]
'''
