[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'source ~/.vim/rc/plugins/dein.rc.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# colorschemeはLazyできないようなのでこっち
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <silent> <Leader>gs :<C-u>Gstatus<CR>
  nnoremap <silent> <Leader>gd :<C-u>Gvdiff<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
if = '!IsPowerlineEnabled()'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
if = 'v:version == 704 && has("patch786") || v:version >= 705 || has("nvim")'
hook_add = '''
  let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'thinca/vim-themis'
if = 'IsHomePC()'
hook_add = 'source ~/.vim/rc/plugins/vim-themis.rc.vim'
