[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# colorschemeはLazyできないようなのでこっち
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'itchyny/lightline.vim'
if = '!IsPowerlineEnabled()'

[[plugins]]
repo = 'thinca/vim-themis'
if = 'IsHomePC()'

[[plugins]]
repo = 'syngan/vim-vimlint'
depends = [ 'vim-vimlparser' ]

[[plugins]]
repo = 'ynkdir/vim-vimlparser'
