[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# colorschemeはLazyできないようなのでこっち
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'itchyny/lightline.vim'
if = '!IsPowerlineEnabled()'

[[plugins]]
repo = 'thinca/vim-themis'
if = 'IsHomePC()'
hook_add = 'source ~/.vim/rc/plugins/vim-themis.rc.vim'
