[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'source ~/.vim/rc/plugins/dein.rc.vim'

# colorschemeはLazyできないようなのでこっち
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <silent> <Leader>gs :<C-u>Gstatus<CR>
  nnoremap <silent> <Leader>gd :<C-u>Gvdiff<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
if = 'v:version == 704 && has("patch786") || v:version >= 705 || has("nvim")'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'nixprime/cpsm'
if = '!IsWindows()'
build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'vim-scripts/smarty-syntax'

[[plugins]]
repo = 'lambdalisue/vim-diffa'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'jwalton512/vim-blade'

[[plugins]]
repo = 'dag/vim-fish'
