hook_add = '''
  " Vim
  let g:vimsyntax_noerror = 1

  " Bash
  let g:is_bash = 1

  " python.vim
  let g:python_highlight_all = 1

  " markdown colors
  " http://mattn.kaoriya.net/software/vim/20140523124903.htm
  let g:markdown_fenced_languages = [
        \   'css',
        \   'javascript',
        \   'js=javascript',
        \   'json=javascript',
        \   'xml',
        \   'vim',
        \   'php',
        \ ]

  " Folding
  let g:xml_syntax_folding = 1

  " Update filetype
  autocmd MyAutocmd BufWritePost * nested
        \ if &l:filetype ==# '' || exists('b:ftdetect') |
        \   unlet! b:ftdetect |
        \   filetype detect |
        \ endif
'''

[ftplugin]
_ = '''
  " Disable automatically insert comment
  setl formatoptions-=ro
  setl formatoptions+=mMBl

  " Disable auto wrap
  if &l:textwidth != 70 && &filetype !=# 'help'
    setlocal textwidth=0
  endif

  " Use foldCCtext()
  if &filetype !=# 'help'
    setlocal foldtext=FoldCCtext()
  endif

  if !&l:modifiable
    setlocal nofoldenable
    setlocal foldcolumn=0

    if v:version >= 703
      setlocal colorcolumn=
    endif
  endif
'''

python = '''
  setlocal foldmethod=indent
  setlocal textwidth=80
  setlocal smarttab
  setlocal expandtab
  setlocal nosmartindent
'''

html = '''
  setlocal path+=./;/
'''

vim = '''
  " setlocal foldmethod=marker
'''

toml = '''
  syntax sync minlines=500
'''

help = '''
  setlocal iskeyword+=:
  setlocal iskeyword+=#
  setlocal iskeyword+=-

  nnoremap <silent> <buffer> q :q<CR>
'''

php = '''
  setlocal colorcolumn=
  setlocal nowrap
'''

smarty = '''
  setlocal colorcolumn=
  setlocal nowrap
'''

sql = '''
  if executable('sql-formatter')
    setlocal formatexpr=
    setlocal formatprg=sql-formatter
  endif
'''

markdown = '''
  let b:not_del_last_whitespaces = 1

  setlocal colorcolumn=
  setlocal wrap
'''

scss = '''
  setlocal shiftwidth=2
  setlocal iskeyword+=-
'''

css = '''
  setlocal iskeyword+=-
'''

blade = '''
  let b:caw_wrap_oneline_comment = [ '{{--', '--}}' ]
'''
