[[plugins]]
repo = 'Shougo/vimproc.vim'
  [plugins.build]
  windows = 'tools\\update-all-mingw'
  cygwin = 'make -f make_cygwin.mak'
  mac = 'make -f make_mak.mak'
  linux = 'make'
  unix = 'gmake'

# colorschemeはLazyできないようなのでこっち
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'w0ng/vim-hybrid'

# 環境次第では無効化される
[[plugins]]
repo = 'itchyny/lightline.vim'
disabled = 'IsPowerlineEnabled()'

# vim:set sw=2:
