[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'Shougo/vimproc.vim'
vim_version = '7.3.885'
on_i = 1
disabled = '!has("lua")'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = [ 'Shougo/neocomplete.vim', 'Shougo/neosnippet-snippets' ]
on_i = 1
on_ft = 'snippet'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'
on_path = '.*'
on_cmd = 'VimFiler'

[[plugins]]
repo = 'tyru/eskk.vim'
on_map = [ [ 'i', '<Plug>' ], [ 'c', '<Plug>' ] ]

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
depends = 'Shougo/unite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'

[[plugins]]
repo = 'thinca/vim-ref'
external_commands = 'lynx'
on_map = [ [ 'nx', '<Plug>', 'K' ] ]

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = [
  'thinca/vim-quickrun',
  'Shougo/vimproc.vim',
  'osyo-manga/shabadou.vim',
]
on_cmd = 'WatchdogsRun'
on_i = 1

[[plugins]]
repo = 'KazuakiM/vim-qfsigns'
depends = 'osyo-manga/vim-watchdogs'
on_source = 'vim-watchdogs'

[[plugins]]
repo = 'KazuakiM/vim-qfstatusline'
depends = 'osyo-manga/vim-watchdogs'
on_source = 'vim-watchdogs'
disabled = 'IsPowerlineEnabled()'

[[plugins]]
repo = 'syngan/vim-vimlint'
depends = [ 'ynkdir/vim-vimlparser', 'osyo-manga/vim-watchdogs' ]
on_source = 'vim-watchdogs'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_path = '.*'

[[plugins]]
repo = 'vim-jp/vital.vim'
on_cmd = 'Vitalize'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = '<Plug>'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '<Plug>'
on_func = 'anzu#'

[[plugins]]
repo = 'tyru/restart.vim'
gui = 1
on_cmd = [ 'Restart', 'RestartWithSession' ]

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'kana/vim-operator-user'
on_map = [ [ 'nx', '<Plug>' ] ]

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
on_map = '<Plug>'

# TODO こいつをうまくロードする方法を考える
[[plugins]]
repo = 'lambdalisue/vim-unified-diff'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'lilydjwg/colorizer'
on_cmd = [ 'ColorToggle', 'ColorHighlight', 'ColorClear' ]
on_ft = [ 'smarty', 'html', 'css', 'php' ]

[[plugins]]
repo = 'kannokanno/previm'
depends = 'tyru/open-browser.vim'
on_cmd = 'PrevimOpen'
disabled = '!IsHomePC()'

[[plugins]]
repo = 'smarty-syntax'
on_ft = 'smarty'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = [ 'scala', 'sbt' ]
disabled = '!IsHomePC()'

[[plugins]]
repo = 'groenewege/vim-less'
on_ft = 'less'
disabled = '!IsHomePC()'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = [ 'coffee', 'markdown' ]
disabled = '!IsHomePC()'

[[plugins]]
repo = 'gre/play2vim'
on_ft = [ 'play2-conf', 'play2-routes' ]
disabled = '!IsHomePC()'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'
disabled = '!IsHomePC()'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
depends = 'Shougo/vimproc.vim'
external_commands = 'ghc-mod'
on_ft = 'haskell'
disabled = '!IsHomePC()'

[[plugins]]
repo = 'benjifisher/matchit.zip'
on_map = [
  [ 'nxo', '%', 'g%' ],
]

[[plugins]]
repo = 'sudo.vim'
on_path = 'sudo:.*'

[[plugins]]
repo = 'cohama/agit.vim'
depends = 'tpope/vim-fugitive'
on_cmd = [ 'Agit', 'AgitFile' ]

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_path = '.*'

[[plugins]]
repo = 'yyotti/neosnippet-additional'
depends = 'Shougo/neosnippet.vim'
on_source = 'neosnippet.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'LeafCage/foldCC.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_path = '.*'
on_cmd = [
  'Git', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge', 'Gpull', 'Gpush',
  'Gfetch', 'Ggrep', 'Glgrep', 'Glog', 'Gllog', 'Gedit', 'Gsplit', 'Gvsplit',
  'Gtabedit', 'Gpedit', 'Gread', 'Gwrite', 'Gwq', 'Gdiff', 'Gsdiff', 'Gvdiff',
  'Gmove', 'Gremove', 'Gblame', 'Gbrowse',
]
augroup = 'fugitive'

[[plugins]]
repo = 'idanarye/vim-merginal'
depends = 'tpope/vim-fugitive'
augroup = 'merginal'
on_cmd = [
  'Merginal', 'MerginalToggle', 'MerginalClose',
]

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'unite.vim'
on_cmd = 'JunkfileOpen'

[[plugins]]
repo = 'simeji/winresizer'
on_cmd = 'WinResizerStartResize'

[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
on_map = '<Plug>'
on_source = 'unite.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
on_path = '.*'
disabled = '!has("conceal")'

[[plugins]]
repo = 'tpope/vim-repeat'
on_source = 'vim-easymotion'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'
on_map = '<Plug>'

# TODO unite-todolistを公開したら記述

# vim:set sw=2:
