# ~/にscalaディレクトリとplayディレクトリへのシンボリックリンクを作成すること
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

alias vi='gvim'
alias vim='gvim'

# git settings
source ~/opt/bash/git-completion.bash
GIT_PS1_SHOWDIRTYSTATE=true
export PS1='\[\033[32m\]\u@\h\[\033[00m\]:\[\033[34m\]\w\[\033[31m\]$(__git_ps1)\[\033[00m\]\$ '
