[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'PProvost/vim-ps1'

[[plugins]]
repo = 'blueyed/smarty.vim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'jwalton512/vim-blade'
if = 0

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
if = 0

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
if = 0
on_ft = 'haskell'
hook_post_source = '''
let g:haskell_indent_disable = 1
'''

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
depends = 'yajs.vim'
hook_add = '''
let g:vim_jsx_pretty_colorful_config = 1
'''
