[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# TODO ???
[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'chemzqm/vim-easygit'

[[plugins]]
repo = 'chemzqm/denite-git'
depends = [ 'vim-easygit' ]
if = 'exists(":python3") ==# 2 && matchstr(execute("python3 import platform; print(platform.python_version())", "silent!"), "\d\+\.\d\+\.\d\+") >=# "3.5.0"'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
if = 'v:version == 704 && has("patch786") || v:version >= 705 || has("nvim")'

[[plugins]]
repo = 'vim-scripts/smarty-syntax'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'jwalton512/vim-blade'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
hook_add = '''
  let g:haskell_indent_disable = 1
'''

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
