#!/bin/sh

REFS_DIR=$HOME/.vim/refs
PHP_MANUAL_DIR=$REFS_DIR/php-chunked-xhtml

if [ -e "$PHP_MANUAL_DIR" ]; then
        exit 0
fi

wget -O /tmp/php_manual_ja.tar.gz http://jp2.php.net/get/php_manual_ja.tar.gz/from/this/mirror

mkdir -p "$REFS_DIR"
cd "$REFS_DIR"
tar xzf /tmp/php_manual_ja.tar.gz
