export LANG=ja_JP.UTF-8
export LESSCHARSET=utf-8
export JLESSCHARSET=japanese-utf-8
export PAGER='less -isr'
# export LSCOLORS=gxfxcxdxbxegedabagacad
export TERM=xterm-256color

# `brew shellenv` is too late.
if [[ -d "${HOME}/.linuxbrew" ]]; then
  export HOMEBREW_PREFIX="${HOME}/.linuxbrew"
elif [[ -d /home/linuxbrew/.linuxbrew ]]; then
  export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
fi

if [[ ${HOMEBREW_PREFIX} != '' ]]; then
  export HOMEBREW_CELLAR="${HOMEBREW_PREFIX}/Cellar"
  export HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}/Homebrew"
  export MANPATH="${HOMEBREW_PREFIX}/share/man:$MANPATH"
  export INFOPATH="${HOMEBREW_PREFIX}/share/info:$INFOPATH"

  path=(
  ${HOMEBREW_PREFIX}/bin(N-/)
  ${HOMEBREW_PREFIX}/sbin(N-/)
  $path
  )
fi

# TODO Check
path=(
~/bin(N-/)
~/.bin(N-/)
~/.local/bin(N-/)
~/.cabal/bin(N-/)
~/.composer/vendor/bin(N-/)
/usr/local/go/bin(N-/)
$DOTFILES/scripts/git/subcommands(N-/)
$HOME/.nodebrew/current/bin(N-/)
$HOME/.yarn/bin(N-/)
${XDG_CONFIG_HOME}/composer/vendor/bin(N-/)
$path
)

if (( ${+commands[vim]} )); then
  export EDITOR=vim
fi

if (( ${+commands[go]} )); then
  export GOPATH=$XDG_DATA_HOME/go
  path=($GOPATH/bin(N-/) $path)
fi

if (( ${+commands[wcwidth-cjk]} )); then
  export LD_PRELOAD=/usr/local/lib/wcwidth-cjk.so
fi

if (( ${+commands[tig]} )); then
  export TIGRC_USER=$XDG_CONFIG_HOME/tig/tigrc
fi

if (( ${+commands[less]} )); then
  export LESSHISTFILE=$XDG_CACHE_HOME/less/history
  export LESSKEY=$XDG_CONFIG_HOME/less/key
fi

skip_global_compinit=1
