export LANG=ja_JP.UTF-8
export LESSCHARSET=utf-8
export JLESSCHARSET=japanese-utf-8
export PAGER='less -isr'
# TODO
# export LSCOLORS=gxfxcxdxbxegedabagacad

if [[ $TMUX == '' ]]; then
  export TERM=xterm-256color

  path=(
  ~/bin(N-/)
  ~/.local/bin(N-/)
  ~/.cabal/bin(N-/)
  ~/.composer/vendor/bin(N-/)
  /usr/local/go/bin(N-/)
  ~/.dotfiles/scripts/git/subcommands(N-/)
  $path
  )
fi

if (( ${+commands[vim]} )); then
  export EDITOR=vim
fi

if (( ${+commands[go]} )); then
  export GOPATH=$XDG_DATA_HOME/go
  path=($GOPATH/bin $path)
fi

if (( ${+commands[wcwidth-cjk]} )); then
  export LD_PRELOAD=/usr/local/lib/wcwidth-cjk.so
fi

if (( ${+commands[tig]} )); then
  export TIGRC_USER=$XDG_CONFIG_HOME/tig/tigrc
fi

if (( ${+commands[less]} )); then
  export LESSHISTFILE=$XDG_CACHE_HOME/less/history
  export LESSKEY=$XDG_CONFIG_HOME/less/key
fi

if (( ${+commands[wget]} )); then
  export WGETRC=$XDG_CONFIG_HOME/wget/wgetrc
fi

skip_global_compinit=1
