export LANG=ja_JP.UTF-8
export LESSCHARSET=utf-8
export JLESSCHARSET=japanese-utf-8
export PAGER='less -isr'
# TODO
# export LSCOLORS=gxfxcxdxbxegedabagacad

# XDG Base Directory
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [[ $TMUX == '' ]]; then
  export TERM=xterm-256color

  path=(
  ~/bin(N-/)
  ~/.local/bin(N-/)
  ~/.cabal/bin(N-/)
  ~/.composer/vendor/bin(N-/)
  /usr/local/go/bin(N-/)
  ~/.dotfiles/scripts/git/subcommands(N-/)
  $path
  )
fi

if (( ${+commands[vim]} )); then
  export EDITOR=vim
fi

if (( ${+commands[go]} )); then
  export GOPATH=$XDG_DATA_HOME/go
  path=($GOPATH/bin $path)
fi

if (( ${+commands[wcwidth-cjk]} )); then
  export LD_PRELOAD=/usr/local/lib/wcwidth-cjk.so
fi

if (( ${+commands[tig]} )); then
  export TIGRC_USER=$XDG_CONFIG_HOME/tig/tigrc
fi

skip_global_compinit=1
