export LANG=ja_JP.UTF-8
export LESSCHARSET=utf-8
export JLESSCHARSET=japanese-utf-8
export PAGER='less -isr'
# TODO
# export LSCOLORS=gxfxcxdxbxegedabagacad
export XDG_CONFIG_HOME=$HOME/.config

if [[ $TMUX == '' ]]; then
  export TERM=xterm-256color

  path=(
  ~/bin(N-/)
  ~/.composer/vendor/bin(N-/)
  /usr/local/go/bin(N-/)
  $path
  )
fi

if (( ${+commands[vim]} )); then
  export EDITOR=vim
fi

if (( ${+commands[go]} )); then
  export GOPATH=$HOME/.go
  path=($GOPATH/bin $path)
fi

skip_global_compinit=1
