[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
rev = 'e5313e5e4ab26ee66447abfbe798c8b8c407d72c'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tyru/eskk.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = [ 'neosnippet-snippets' ]
on_i = 1
on_ft = 'snippet'
on_source = 'unite.vim'

[[plugins]]
repo = 'yyotti/neosnippet-additional'
depends = 'neosnippet.vim'
on_source = 'neosnippet.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = '<Plug>'
on_path = '.*'

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_func = 'fugitive#head'

[[plugins]]
repo = 'cohama/agit.vim'
on_path = [ 'Agit', 'AgitFile' ]

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_path = '.*'

[[plugins]]
repo = 'thinca/vim-ref'
if = 'executable("lynx")'
on_map = '<Plug>'

[[plugins]]
repo = 'tpope/vim-repeat'

# FIXME Lazyだと最初のコマンドで問題が出る
[[plugins]]
repo = 'easymotion/vim-easymotion'
depends = 'vim-repeat'
on_map = '<Plug>'

[[plugins]]
repo = 'tyru/caw.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '<Plug>'
on_func = 'anzu#'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = [ [ 'nx', '<Plug>' ] ]

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'vim-scripts/sudo.vim'
on_path = 'sudo:.*'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'LeafCage/foldCC.vim'
on_path = '.*'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-scripts/smarty-syntax'
on_ft = 'smarty'

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = [ 'smarty', 'html', 'css', 'php' ]

[[plugins]]
repo = 'yyotti/vim-lintexec.nvim'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'
on_map = '<Plug>'

[[plugins]]
repo = 'lambdalisue/vim-unified-diff'
on_path = '.*'

[[plugins]]
repo = 'ysktti/vim-autoupload'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
on_i = 1

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'benjifisher/matchit.zip'
on_map = [
  [ 'nxo', '%', 'g%' ],
]

[[plugins]]
repo = 'yyotti/unite-googletasks'
depends = 'unite.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'yyotti/unite-tasks.vim'
depends = 'unite.vim'
on_source = 'unite.vim'

# 以下、家PC用
[[plugins]]
repo = 'tyru/open-browser.vim'
if = 'IsHomePC()'

[[plugins]]
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_ft = 'markdown'
if = 'IsHomePC()'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'
if = 'IsHomePC()'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
depends = 'vimproc.vim'
on_ft = 'haskell'
if = 'executable("ghc-mod")'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = [ 'scala', 'sbt' ]
if = 'IsHomePC()'

[[plugins]]
repo = 'gre/play2vim'
on_ft = [ 'play2-conf', 'play2-routes' ]
if = 'IsHomePC()'
