[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = [ 'Shougo/deoplete.nvim', 'Shougo/neosnippet-snippets' ]
on_i = 1
on_ft = 'snippet'
on_unite = [ 'neosnippet', 'neosnippet/user', 'neosnippet/runtime' ]

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'
on_path = '.*'
on_cmd = 'VimFiler'

[[plugins]]
repo = 'tyru/eskk.vim'
on_map = [ [ 'i', '<Plug>' ], [ 'c', '<Plug>' ] ]

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_unite = 'junkfile'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_path = '.*'
on_cmd = [
  'Git', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge', 'Gpull', 'Gpush',
  'Gfetch', 'Ggrep', 'Glgrep', 'Glog', 'Gllog', 'Gedit', 'Gsplit', 'Gvsplit',
  'Gtabedit', 'Gpedit', 'Gread', 'Gwrite', 'Gwq', 'Gdiff', 'Gsdiff', 'Gvdiff',
  'Gmove', 'Gremove', 'Gblame', 'Gbrowse',
]
augroup = 'fugitive'

[[plugins]]
repo = 'idanarye/vim-merginal'
depends = 'tpope/vim-fugitive'
augroup = 'merginal'
on_cmd = [
  'Merginal', 'MerginalToggle', 'MerginalClose',
]
