[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = [ 'Shougo/deoplete.nvim', 'Shougo/neosnippet-snippets' ]
on_i = 1
on_ft = 'snippet'
on_unite = [ 'neosnippet', 'neosnippet/user', 'neosnippet/runtime' ]

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'
on_path = '.*'
on_cmd = 'VimFiler'

[[plugins]]
repo = 'tyru/eskk.vim'
on_map = [ [ 'i', '<Plug>' ], [ 'c', '<Plug>' ] ]

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_unite = 'junkfile'
