[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tyru/eskk.vim'

# colorschemeはLazyできないようなのでこっち
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'itchyny/lightline.vim'
disabled = 'IsPowerlineEnabled()'
